/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsInt,
  Min,
  Max,
  IsOptional,
  IsDate,
  IsString,
  MaxLength,
  IsNumber,
  ValidateNested,
} from "class-validator";

import { Type } from "class-transformer";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { PaymentsUpdateManyWithoutOrdersInput } from "./PaymentsUpdateManyWithoutOrdersInput";
import { OrderItemUpdateManyWithoutOrdersInput } from "./OrderItemUpdateManyWithoutOrdersInput";

@InputType()
class OrderUpdateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  orderId?: number | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  orderDate?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  shippingAddress?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  status?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  totalAmount?: number | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => PaymentsUpdateManyWithoutOrdersInput,
  })
  @ValidateNested()
  @Type(() => PaymentsUpdateManyWithoutOrdersInput)
  @IsOptional()
  @Field(() => PaymentsUpdateManyWithoutOrdersInput, {
    nullable: true,
  })
  paymentsItems?: PaymentsUpdateManyWithoutOrdersInput;

  @ApiProperty({
    required: false,
    type: () => OrderItemUpdateManyWithoutOrdersInput,
  })
  @ValidateNested()
  @Type(() => OrderItemUpdateManyWithoutOrdersInput)
  @IsOptional()
  @Field(() => OrderItemUpdateManyWithoutOrdersInput, {
    nullable: true,
  })
  orderItems?: OrderItemUpdateManyWithoutOrdersInput;
}

export { OrderUpdateInput as OrderUpdateInput };
