/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsInt,
  Min,
  Max,
  IsOptional,
  IsString,
  MaxLength,
  IsNumber,
  ValidateNested,
} from "class-validator";
import { CategoryWhereUniqueInput } from "../../category/base/CategoryWhereUniqueInput";
import { Type } from "class-transformer";
import { ReviewsUpdateManyWithoutProductsInput } from "./ReviewsUpdateManyWithoutProductsInput";
import { WishlistItemsUpdateManyWithoutProductsInput } from "./WishlistItemsUpdateManyWithoutProductsInput";
import { CartItemsUpdateManyWithoutProductsInput } from "./CartItemsUpdateManyWithoutProductsInput";
import { OrderItemUpdateManyWithoutProductsInput } from "./OrderItemUpdateManyWithoutProductsInput";

@InputType()
class ProductUpdateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  productId?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  price?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  stockQuantity?: number | null;

  @ApiProperty({
    required: false,
    type: () => CategoryWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CategoryWhereUniqueInput)
  @IsOptional()
  @Field(() => CategoryWhereUniqueInput, {
    nullable: true,
  })
  category?: CategoryWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => ReviewsUpdateManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => ReviewsUpdateManyWithoutProductsInput)
  @IsOptional()
  @Field(() => ReviewsUpdateManyWithoutProductsInput, {
    nullable: true,
  })
  reviewsItems?: ReviewsUpdateManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: () => WishlistItemsUpdateManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => WishlistItemsUpdateManyWithoutProductsInput)
  @IsOptional()
  @Field(() => WishlistItemsUpdateManyWithoutProductsInput, {
    nullable: true,
  })
  wishlistItemsItems?: WishlistItemsUpdateManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: () => CartItemsUpdateManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => CartItemsUpdateManyWithoutProductsInput)
  @IsOptional()
  @Field(() => CartItemsUpdateManyWithoutProductsInput, {
    nullable: true,
  })
  cartItemsItems?: CartItemsUpdateManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: () => OrderItemUpdateManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => OrderItemUpdateManyWithoutProductsInput)
  @IsOptional()
  @Field(() => OrderItemUpdateManyWithoutProductsInput, {
    nullable: true,
  })
  orderItems?: OrderItemUpdateManyWithoutProductsInput;
}

export { ProductUpdateInput as ProductUpdateInput };
