/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsInt,
  Min,
  Max,
  ValidateNested,
} from "class-validator";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { OrderUpdateManyWithoutUsersInput } from "./OrderUpdateManyWithoutUsersInput";
import { Type } from "class-transformer";
import { ReviewsUpdateManyWithoutUsersInput } from "./ReviewsUpdateManyWithoutUsersInput";
import { WishlistUpdateManyWithoutUsersInput } from "./WishlistUpdateManyWithoutUsersInput";
import { ShoppingCartUpdateManyWithoutUsersInput } from "./ShoppingCartUpdateManyWithoutUsersInput";

@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  roles?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phoneNumber?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  address?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  userId?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  passwordHash?: string | null;

  @ApiProperty({
    required: false,
    type: () => OrderUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => OrderUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => OrderUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  orders?: OrderUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => ReviewsUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => ReviewsUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => ReviewsUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  reviewsItems?: ReviewsUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => WishlistUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => WishlistUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => WishlistUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  wishlists?: WishlistUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => ShoppingCartUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => ShoppingCartUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => ShoppingCartUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  shoppingCarts?: ShoppingCartUpdateManyWithoutUsersInput;
}

export { UserUpdateInput as UserUpdateInput };
