/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ShoppingCart } from "./ShoppingCart";
import { ShoppingCartCountArgs } from "./ShoppingCartCountArgs";
import { ShoppingCartFindManyArgs } from "./ShoppingCartFindManyArgs";
import { ShoppingCartFindUniqueArgs } from "./ShoppingCartFindUniqueArgs";
import { CreateShoppingCartArgs } from "./CreateShoppingCartArgs";
import { UpdateShoppingCartArgs } from "./UpdateShoppingCartArgs";
import { DeleteShoppingCartArgs } from "./DeleteShoppingCartArgs";
import { CartItemsFindManyArgs } from "../../cartItems/base/CartItemsFindManyArgs";
import { CartItems } from "../../cartItems/base/CartItems";
import { User } from "../../user/base/User";
import { ShoppingCartService } from "../shoppingCart.service";
@graphql.Resolver(() => ShoppingCart)
export class ShoppingCartResolverBase {
  constructor(protected readonly service: ShoppingCartService) {}

  async _shoppingCartsMeta(
    @graphql.Args() args: ShoppingCartCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ShoppingCart])
  async shoppingCarts(
    @graphql.Args() args: ShoppingCartFindManyArgs
  ): Promise<ShoppingCart[]> {
    return this.service.shoppingCarts(args);
  }

  @graphql.Query(() => ShoppingCart, { nullable: true })
  async shoppingCart(
    @graphql.Args() args: ShoppingCartFindUniqueArgs
  ): Promise<ShoppingCart | null> {
    const result = await this.service.shoppingCart(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ShoppingCart)
  async createShoppingCart(
    @graphql.Args() args: CreateShoppingCartArgs
  ): Promise<ShoppingCart> {
    return await this.service.createShoppingCart({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => ShoppingCart)
  async updateShoppingCart(
    @graphql.Args() args: UpdateShoppingCartArgs
  ): Promise<ShoppingCart | null> {
    try {
      return await this.service.updateShoppingCart({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ShoppingCart)
  async deleteShoppingCart(
    @graphql.Args() args: DeleteShoppingCartArgs
  ): Promise<ShoppingCart | null> {
    try {
      return await this.service.deleteShoppingCart(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [CartItems], { name: "cartItemsItems" })
  async findCartItemsItems(
    @graphql.Parent() parent: ShoppingCart,
    @graphql.Args() args: CartItemsFindManyArgs
  ): Promise<CartItems[]> {
    const results = await this.service.findCartItemsItems(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  async getUser(@graphql.Parent() parent: ShoppingCart): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
